print("Hello, GitHub!")
print("I am learning Python.")
print("This is my first GitHub project.")
print("I will become a Python developer!")
print("it is good for learning git bash for a python devolper")
print("Day 4: I am improving my Git skills!")
print("Day 5: I am learning Git!")